### ISSUE TITLE
about premission 

### ISSUE THREAD

**Issue by codeRemark** [GoogleChromeLabs/serial-terminal#24]
I face a strange question, I use the code connect to serial port ,
 it works fine if I through "http://localhost/index.html'  , the index.html do connect serial port . it works fine, connected and receive data from serial port .

but if I deploy it on server, and access the page from client computer, 

the url like 'http://192.168.10.123/index.html' , then it always report not  'serial' , 

I trace the code with log : `console.log("navigator?", navigator, navigator.serial);`

it show 'serial'  is undefined .  

confuse with this issue, I assume it relative to browser permission issue , but after struggle googling 

no any useful information yet,

I am appreciate with your help !

thanks

**Comment by reillyeon** [comment]
The Web Serial API is only available in a [secure context](https://html.spec.whatwg.org/multipage/webappapis.html#secure-context) which means a site served over HTTPS (or localhost, for development purposes).

**Comment by codeRemark** [comment]
hi, many thanks for your  reply, 

so if possible we can make a serial port plugin that install on chrome browser client for this purpose ?

I just need read serial port data

**Comment by reillyeon** [comment]
The solution is to use an HTTPS connection instead of HTTP.
