### ISSUE TITLE
Shared hosting?

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [GoogleChromeLabs/serial-terminal#35]
Hello, I'm using a shared hosting. I don't have access to add or install npm. Is it possible to do this without doing that steps?

Joseph

**Comment by reillyeon** [comment]
NPM is required to build the code but once you run `npm build` the output in the `dist` folder is all static content which could be hosted anywhere.

**Comment by Therealjosephchrzempiec** [comment]
Is there a demo for this?


Joseph

**Comment by reillyeon** [comment]
This is how this project is hosted on https://googlechromelabs.github.io/serial-terminal. The static content is built with `npm build` and then uploaded to GitHub Pages (which only handles static content) with `npm publish`.

**Comment by Therealjosephchrzempiec** [comment]
Hello in the dist folder nothing is there.

**Comment by reillyeon** [comment]
Did you follow the build instructions? https://github.com/GoogleChromeLabs/serial-terminal#building

**Comment by Therealjosephchrzempiec** [comment]
When I tried to install npm in there I get:

`C:\Users\jJc\Documents\serial-terminal-main\serial-terminal-main>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 745 packages in 4.82s

104 packages are looking for funding
  run `npm fund` for details

found 4 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details`

then I do npm run build and get:

WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.69.0 compiled with 3 warnings in 15576 ms

and the run one lets me run it with port 8080.

**Comment by Therealjosephchrzempiec** [comment]
I even did the npm audit fix. But Nothing in the Dist folder.

**Comment by Therealjosephchrzempiec** [comment]
Hello, I finall got the files in the dist. I had to do is 3 times then I was able to see all the files.
