### ISSUE TITLE
local dev build not working

### ISSUE THREAD

**Issue by Kriechi** [GoogleChromeLabs/serial-terminal#45]
Running `npm start` gives meaningful output, but browsing to `http://localhost:8080/` or any of the other URLs just give a `Cannot GET /` error message.

Adding `/index.html` to the URL does solve it either.

Using `npm run build` produces a working bundle and index.html in the `dist/` folder, but when using `npm start` this folder gets cleared and stays empty.

How is the local dev environment supposed to be started?

**Comment by reillyeon** [comment]
It looks like something recently broke in webpack-dev-server. Fixed in 85bb3e4df785e671c6c19b6a1e7b169d4c72e116.
