### ISSUE TITLE
crashing serial at-cmd port

### ISSUE THREAD

**Issue by MarPiSora** [GoogleChromeLabs/serial-terminal#62]
Using: Win10 - Chrome Version 118.0.5993.89 (Official Build) (64-bit)
Since recently connecting to an at-cmd serial port of a Quectel EG-25 based USB modem is crashing the serial port.
Device disappears from device manager and I need to unplug and plug in again. 
BR: 115200 , 8N1
All worked well some time ago. Device could be accessed without problems using other serial terminal applications.

As well the Modem port is not listed anymore (which was available in one of the last releases).

Is it possible to show Modem com port again in port selection window?
What might be the cause for crashing the serial port?

```
<CONNECTED>
<ERROR: An unknown system error has occurred.>
<ERROR: An unknown system error has occurred.>
<ERROR: An unknown system error has occurred.>
<ERROR: An unknown system error has occurred.>
<ERROR: An unknown system error has occurred.>
<ERROR: An unknown system error has occurred.>
<ERROR: An unknown system error has occurred.>
<ERROR: An unknown system error has occurred.>
<ERROR: An unknown system error has occurred.>
<ERROR: An unknown system error has occurred.>
<ERROR: An unknown system error has occurred.>
<ERROR: An unknown system error has occurred.>
<ERROR: An unknown system error has occurred.>
<ERROR: An unknown system error has occurred.>
<ERROR: An unknown system error has occurred.>
<ERROR: An unknown system error has occurred.>
<ERROR: An unknown system error has occurred.>
<ERROR: An unknown system error has occurred.>
<ERROR: Break received>
<ERROR: Break received>
<ERROR: Break received>
<ERROR: Break received>
<ERROR: Break received>
```

**Comment by reillyeon** [comment]
Can you confirm that the device does not disappear from the Device Manager when connecting to it with a different terminal application? Disappearing like this indicates that the device has encountered some kind of fatal error and that isn't something an application simply connecting to it should be able to easily trigger. When I have seen problems like this in the past it has been due to a faulty USB cable.

**Comment by MarPiSora** [comment]
Thanks for your reply...I made some more tests and the device crashes as well using a different terminal application.
All is well if I frist connect to modem port and send an 'at' and then connect the chrome serial terminal to the at-cmd port..
I got a second device of same type and do not have any problem.
Please excuse pushing this to the terminal.
