### ISSUE TITLE
Question about handle disconnect USB in any time

### ISSUE THREAD

**Issue by Blucbo** [GoogleChromeLabs/serial-terminal#7]
Hi, maybe you have an idea of how to capture the communication loss if the wire accidentally malfunctioned.

I can't handle the error if somebody accidentally moves USB cable(

Case: 
1. success connect
2. send data
3. somebody accidentally moves USB
4. send data don't work

**Comment by reillyeon** [comment]
I assume that you mean the USB cable is temporarily disconnected. In that case the host is going to have to re-enumerate the USB device and from the application's perspective that is going to look like the port was disconnected (causing a fatal error to be reported on the WritableStream) and then reconnected.

Once persistent permissions and connect/disconnect events are implemented (Chromium issues [908836](https://bugs.chromium.org/p/chromium/issues/detail?id=908836) and [918216](https://bugs.chromium.org/p/chromium/issues/detail?id=918216)) you will be able to listen for a connect event for the port and re-open it to resume sending data to the device.

**Comment by Blucbo** [comment]
Thank you so much for your answer

**Comment by reillyeon** [comment]
Closing this issue now. The demo will be updated with an example of listening for connect and disconnect events when they are implemented.
